package com.textanimation;

import android.graphics.Paint;
import android.graphics.Path;
import android.graphics.PathMeasure;
import android.graphics.RectF;
import android.graphics.drawable.Drawable;
import android.text.TextWatcher;
import android.view.ViewGroup;

import java.lang.ref.WeakReference;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AnimationState {
    public String prevText = "";
    public boolean textDirty = true;
    public TextWatcher textWatcher;
    public int prevLen = 0;
    public int prevLastLineStart = 0;
    public final Map<Integer, CharAnimData> charStartTimes = new HashMap<>();
    public final List<Particle> particles = new ArrayList<>();
    public final List<GhostGlyph> ghosts = new ArrayList<>();
    public boolean hasAnimatingChars = false;
    public boolean animationRunning = false;
    public boolean originalCursorVisible = true;
    public boolean hasOriginalCursorVisible = false;
    public boolean cursorDrawSuppressed = false;
    public boolean originalAllowDrawCursor = true;
    public boolean cursorDrawableReplaced = false;
    public Drawable originalCursorDrawable;
    public float cursorX = -1.0f;
    public float cursorY = -1.0f;
    public float cursorMotion = 0.0f;
    public long cursorBlinkAnchor = 0L;
    public float spaceJumpX = -1.0f;
    public float spaceJumpY = -1.0f;
    public long spaceJumpStartTime = 0L;
    public long enterDiveStartTime = 0L;
    public long backspacePulseStartTime = 0L;
    public long selectionStretchStartTime = 0L;
    public float selectionStretchBoost = 0.0f;
    public int lastSelectionOffset = -1;
    public int lastSelectionStart = -1;
    public int lastSelectionEnd = -1;
    public long selectionEffectStartTime = 0L;
    public float selectionStartX = -1.0f;
    public float selectionStartY = -1.0f;
    public float selectionEndX = -1.0f;
    public float selectionEndY = -1.0f;
    public float selectionStartSnap = 0.0f;
    public float selectionEndSnap = 0.0f;
    public long lastCursorDrawTime = 0L;
    public long cursorWakeTime = 0L;
    public long lastDrawTime = 0L;
    public int drawingDepth = 0;
    public long lastParticleUpdateTime = 0L;
    public long lastTypeTime = 0L;
    public int combo = 0;
    public long shakeStartTime = 0L;
    public float shakeAmp = 0.0f;
    public int shakeSaveCount = -1;
    public long sendPendingTime = 0L;
    public boolean hasSendTarget = false;
    public float sendTargetX = 0.0f;
    public float sendTargetY = 0.0f;
    public WeakReference<ViewGroup> overlayHost;
    public Drawable overlayDrawable;
    public long lastWordTriggerTime = 0L;
    public Paint cursorPaint;
    public Paint particlePaint;
    public Paint particleStrokePaint;
    public Paint particleTextPaint;
    public Paint sharedPaint;
    public Paint comboPaint;
    public Path glyphPath;
    public Path particlePath;
    public PathMeasure pathMeasure;
    public RectF cursorRect;
    public Map<Integer, Object> hiddenSpans;
}
